name: invokeai
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9.13
  - pip=22.2.2

  - pytorch=1.12.1
  - torchvision=0.13.1

  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/invokeai/invokeai-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n invokeai-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```

  - albumentations=1.2.1
  - coloredlogs=15.0.1
  - diffusers=0.6.0
  - einops=0.4.1
  - grpcio=1.46.4
  - humanfriendly=10.0
  - imageio=2.21.2
  - imageio-ffmpeg=0.4.7
  - imgaug=0.4.0
  - kornia=0.6.7
  - mpmath=1.2.1
  - nomkl # arm64 has only 1.0 while x64 needs 3.0
  - numpy=1.23.4
  - omegaconf=2.1.1
  - openh264=2.3.0
  - onnx=1.12.0
  - onnxruntime=1.12.1
  - pudb=2022.1
  - pytorch-lightning=1.7.7
  - scipy=1.9.3
  - streamlit=1.12.2
  - sympy=1.10.1
  - tensorboard=2.10.0
  - torchmetrics=0.10.1
  - py-opencv=4.6.0
  - flask=2.1.3
  - flask-socketio=5.3.0
  - flask-cors=3.0.10
  - eventlet=0.33.1
  - protobuf=3.20.1
  - send2trash=1.8.0
  - transformers=4.23.1
  - torch-fidelity=0.3.0
  - pip:
      - getpass_asterisk
      - dependency_injector==4.40.0
      - realesrgan==0.2.5.0
      - test-tube==0.7.5
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
      - -e git+https://github.com/TencentARC/GFPGAN.git#egg=gfpgan
      - -e git+https://github.com/invoke-ai/clipseg.git@models-rename#egg=clipseg
      - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
